title = "BitXHub configuration file"

solo = false

[port]
  grpc = 60011
  gateway = 9091
  pprof = 53121
  monitor = 40011

[pprof]
  enable = true
  ptype = "http" # including two types: runtime (recommended for use during the development phase) and http
  mode = "memory" # only required for runtime ptype, including two modes: cpu„ÄÅmemory
  duration = "30s" # only required for runtime ptype, every duration will generation a profile.

[monitor]
  enable = true

[gateway]
    allowed_origins = ["*"]

[ping]
  enable = true
  duration = "15s"

[security]
  enable_tls = false
  pem_file_path = "certs/server.pem"
  server_key_path = "certs/server.key"

[limiter]
  interval= "50ms"
  quantum= 500
  capacity= 10000

[log]
  level = "info"
  dir = "logs"
  filename = "bitxhub.log"
  report_caller = false
  [log.module]
    p2p = "info"
    consensus = "info"
    executor = "info"
    router = "info"
    api = "info"
    coreapi = "info"
    storage = "info"

[cert]
  verify = true
  node_cert_path = "certs/node.cert"
  agency_cert_path = "certs/agency.cert"
  ca_cert_path = "certs/ca.cert"

[order]
  plugin = "plugins/raft.so"

[executor]
  type = "serial"  # opensource version only supports serial type, commercial version supports serial and parallel types

[license]
  key = "133847740289a8dc5447bfbaedf10ed5ee9460110e4ba6b455e33cf941253527f18dd721515c5142fcea9b6415ddad6b3f1696011a4bbc86f35833ae9296a3ea"
  verifier = "https://172.16.5.3:11443/v1/validation"

[genesis]
  [[genesis.admins]]
    address = "0xc7F999b83Af6DF9e67d0a37Ee7e900bF38b3D013"
    weight = 1
  [[genesis.admins]]
    address = "0x79a1215469FaB6f9c63c1816b45183AD3624bE34"
    weight = 1
  [[genesis.admins]]
    address = "0x97c8B516D19edBf575D72a172Af7F418BE498C37"
    weight = 1
  [[genesis.admins]]
    address = "0xc0Ff2e0b3189132D815b8eb325bE17285AC898f8"
    weight = 1
  [genesis.strategy]
    AppchainMgr = "SimpleMajority"
    RuleMgr = "SimpleMajority"
    NodeMgr = "SimpleMajority"
    ServiceMgr = "SimpleMajority"