title = "BitXHub configuration file"

solo = false

[port]
  grpc = 60011
  gateway = 9091
  pprof = 53121
  monitor = 40011

[pprof]
  enable = true
  ptype = "http" # including two types: runtime (recommended for use during the development phase) and http
  mode = "memory" # only required for runtime ptype, including two modes: cpu„ÄÅmemory
  duration = "1m" # only required for runtime ptype, every duration will generation a profile.

[monitor]
  enable = true

[gateway]
    allowed_origins = ["*"]

[ping]
  enable = true
  duration = "15s"

[security]
enable_tls = false
pem_file_path = "certs/server.pem"
server_key_path = "certs/server.key"

[log]
  level = "info"
  dir = "logs"
  filename = "bitxhub.log"
  report_caller = false
  [log.module]
    p2p = "info"
    consensus = "debug"
    executor = "info"
    router = "info"
    api = "info"
    coreapi = "info"
    storage = "info"

[cert]
  verify = true

[order]
  plugin = "plugins/rbft.so"

[executor]
  type = "serial"  # opensource version only supports serial type, commercial version supports serial and parallel types
