title = "BitXHub configuration file"

solo = false

[port]
  grpc = 60013
  gateway = 9093
  pprof = 53123

[pprof]
  enable = true

[gateway]
    allowed_origins = ["*"]

[log]
  level = "info"
  dir = "logs"
  filename = "bitxhub.log"
  report_caller = false
  [log.module]
    p2p = "info"
    consensus = "info"
    executor = "info"
    router = "info"
    api = "info"
    coreapi = "info"

[cert]
  verify = true

[order]
  plugin = "plugins/raft3.so"

[genesis]
  [[genesis.admins]]
    address = "0xc7F999b83Af6DF9e67d0a37Ee7e900bF38b3D013"
    weight = 1
  [[genesis.admins]]
    address = "0x79a1215469FaB6f9c63c1816b45183AD3624bE34"
    weight = 1
  [[genesis.admins]]
    address = "0x97c8B516D19edBf575D72a172Af7F418BE498C37"
    weight = 1
  [[genesis.admins]]
    address = "0xc0Ff2e0b3189132D815b8eb325bE17285AC898f8"
    weight = 1
  [genesis.strategy]
    AppchainMgr = "SimpleMajority"
    RuleMgr = "SimpleMajority"
    NodeMgr = "SimpleMajority"
    ServiceMgr = "SimpleMajority"