name: Premo

on:
  pull_request:
    branches:
      - master
      - release-*
jobs:
  bxh_tester:
    name: Run bxh_tester
    runs-on: ubuntu-latest
    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.13
#
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Run bxh_tester
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          cd scripts
#          echo ${{ github.base_ref }}
#          bash bxh_test.sh -b ${{ github.base_ref }}
      - name: Get Mail
        env:
          mail: ${{ github.actor }}
        run: echo ${{ secrets."%mail%" }}

#      - name: Send Mail
#        uses: dawidd6/action-send-mail@master
#        with:
#          server_address: smtp.exmail.qq.com
#          server_port: 465
#          username: ${{ secrets.MAILUSERNAME }}
#          password: ${{ secrets.MAILPASSWORD }}
#          subject: Bxh-teser Test Report
#          body: Hello World
#          to: zhuweijie@hyperchain.cn
#          from: GitHub Actions



